version: 2
updates:
  - package-ecosystem: "bun"
    directories:
      - "/"
      - "/packages/*"
      - "/workers/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
