export default defineNuxtConfig({
  compatibilityDate: "2026-09-25",

  future: {
    compatibilityVersion: 4,
  },

  modules: ["@nuxt/fonts", "@nuxtjs/color-mode", "@nuxt/icon"],

  nitro: {
    preset: "cloudflare_module",
    cloudflare: {
      // cloudflare.config.ts defines the Worker, so Nitro must not write wrangler.json.
      deployConfig: false,
      nodeCompat: true,
    },
  },

  typescript: {
    tsConfig: {
      // Include types generated by `cf workers types` because TypeScript globs skip dot directories.
      include: ["../.cloudflare/types"],
    },
  },

  colorMode: {
    classSuffix: "",
  },

  fonts: {
    families: [{ name: "Inter", weights: [400, 500] }],
  },

  app: {
    head: {
      title: "RSS para Físicos",
      meta: [
        { charset: "utf-8" },
        { name: "viewport", content: "width=device-width, initial-scale=1" },
        {
          name: "description",
          content: "Noticias curadas de física y ciencia para la comunidad científica peruana.",
        },
      ],
    },
  },

  css: ["~/assets/css/main.css"],
});
